export const videoData = [
    {
        id:"17GHS9e6Xu4",
        title:"Why We Laugh : The Neuroscience of Humour - Full Stream",
        description:"Tune into this live stream with Tanmay and Sidharth Warrier (MD, DM Neurology) where they discuss the neuroscience behind humour.",
        channelName:"Honestly by Tanmay Bhat",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjhWBsemL-_0qiUL8CBztox-E6ZmYcVYW-ZxEPQ=s88-c-k-c0x00ffffff-no-rj",
        videoUrl:"https://www.youtube.com/watch?v=17GHS9e6Xu4",
        thumbnail:"https://i.ytimg.com/vi/17GHS9e6Xu4/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDGmr31SQVmSHMwJv_5kH2LSFq6kg",
        time:"10 months ago",
        duration: "1:08:30",
        allNotes: [],
    },
    
    {
        id:"F6qwVcrQB2E",
        title:"WHY DO WE FEEL DEPRESSED? - Full Stream",
        description:"Tune into this live stream with Tanmay and Sidharth Warrier where they discuss the neuroscience behind depression.",
        channelName:"Honestly by Tanmay Bhat",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjhWBsemL-_0qiUL8CBztox-E6ZmYcVYW-ZxEPQ=s88-c-k-c0x00ffffff-no-rj",
        videoUrl:"https://www.youtube.com/watch?v=F6qwVcrQB2E",
        thumbnail:"https://i.ytimg.com/vi/F6qwVcrQB2E/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCG_aWbpUk4CI4JVz9BLkrf7_EzYw",
        time:"10 months ago",
        duration: "1:27:05",
        allNotes: [],
    },

    {
        id:"VLTFfDZ1kpA",
        title:"Why Do We Enjoy Music? - Full Stream",
        description:"Tune into this live stream with me and Siddharth Warrier (MD, DM Neurology) where we discuss the neuroscience behind music.",
        channelName:"Honestly by Tanmay Bhat",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjhWBsemL-_0qiUL8CBztox-E6ZmYcVYW-ZxEPQ=s88-c-k-c0x00ffffff-no-rj",
        videoUrl:"https://www.youtube.com/watch?v=VLTFfDZ1kpA",
        thumbnail:"https://i.ytimg.com/vi/VLTFfDZ1kpA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA8j3CUARzho4AfIFN1UkvI4suA5w",
        time:"9 months ago",
        duration: "1:43:30",
        allNotes: [],
    },

    {
        id:"751tAVlH0Y8",
        title:"Why Do We 'Fall In Love'? - Full Stream",
        description:"Tune into this live stream with me and Sidharth Warrier (MD, DM Neurology) where we discuss the neuroscience behind love",
        channelName:"Honestly by Tanmay Bhat",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjhWBsemL-_0qiUL8CBztox-E6ZmYcVYW-ZxEPQ=s88-c-k-c0x00ffffff-no-rj",
        videoUrl:"https://www.youtube.com/watch?v=751tAVlH0Y8",
        thumbnail:"https://i.ytimg.com/vi/751tAVlH0Y8/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQizXZcqoJl8o61STZ5_h1z95VAg",
        time:"10 months ago",
        duration: "1:49:25",
        allNotes: [],
    },

    {
        id:"mYTjgYKVBRA",
        title:"THE NEUROSCIENCE OF LOVE - PART 2",
        description:"Tune into this live stream with me and Siddharth Warrier (MD, DM Neurology) where we continue our discussion of the neuroscience behind love.",
        channelName:"Honestly by Tanmay Bhat",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjhWBsemL-_0qiUL8CBztox-E6ZmYcVYW-ZxEPQ=s88-c-k-c0x00ffffff-no-rj",
        videoUrl:"https://www.youtube.com/watch?v=mYTjgYKVBRA",
        thumbnail:"https://i.ytimg.com/vi/mYTjgYKVBRA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC4Ca0NL3dZzpI73BEQqStY5kybPQ",
        time:"9 months ago",
        duration: "1:39:50",
        allNotes: [],
    },

    {
        id:"tr0EbFGMaAY",
        title:"Emotions - Part 1: Anatomy and evolution of emotion",
        description:"A discussion on the general neuroanatomy of the brain circuits that analyse emotion, with a more in-depth look at a few specific emotions.",
        channelName:"Siddharth Warrier",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjcdy9X6ctWHgXJIIIKcgqDyHtY6kOQGMW14NhL_bI=s176-c-k-c0x00ffffff-no-rj-mo",
        videoUrl:"https://www.youtube.com/watch?v=tr0EbFGMaAY",
        thumbnail:"https://i.ytimg.com/vi/tr0EbFGMaAY/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBlB8_THch0zEM6RxmYDMgD_5Yg2A",
        time:"11 months ago",
        duration: "16:07",
        allNotes: [],
    },

    {
        id:"Vt4-N5T2IB0",
        title:"Emotions - Part 2: On fear, disgust and anger",
        description:"A discussion on the general neuroanatomy of the brain circuits that analyse emotion, with a more in-depth look at a few specific emotions.",
        channelName:"Siddharth Warrier",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjcdy9X6ctWHgXJIIIKcgqDyHtY6kOQGMW14NhL_bI=s176-c-k-c0x00ffffff-no-rj-mo",
        videoUrl:"https://www.youtube.com/watch?v=Vt4-N5T2IB0",
        thumbnail:"https://i.ytimg.com/vi/Vt4-N5T2IB0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD-fMfGefFnOcYVyUtexHm3wrAPnw",
        time:"11 months ago",
        duration: "14:48",
        allNotes: [],
    },

    {
        id:"dVxd0tsJbVo",
        title:"Emotions - Part 3: On happiness and sadness",
        description:"A discussion on the general neuroanatomy of the brain circuits that analyse emotion, with a more in-depth look at a few specific emotions.",
        channelName:"Siddharth Warrier",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjcdy9X6ctWHgXJIIIKcgqDyHtY6kOQGMW14NhL_bI=s176-c-k-c0x00ffffff-no-rj-mo",
        videoUrl:"https://www.youtube.com/watch?v=dVxd0tsJbVo",
        thumbnail:"https://i.ytimg.com/vi/dVxd0tsJbVo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB21NVn-fsnshoN-r9wfH41IVPqpg",
        time:"11 months ago",
        duration: "9:10",
        allNotes: [],
    },

    {
        id:"8AXJI88mmPw",
        title:"Emotions - Part 4: Why emotions make us human and other questions",
        description:"A discussion on the general neuroanatomy of the brain circuits that analyse emotion, with a more in-depth look at a few specific emotions.",
        channelName:"Siddharth Warrier",
        channelImage:"https://yt3.ggpht.com/ytc/AAUvwnjcdy9X6ctWHgXJIIIKcgqDyHtY6kOQGMW14NhL_bI=s176-c-k-c0x00ffffff-no-rj-mo",
        videoUrl:"https://www.youtube.com/watch?v=8AXJI88mmPw",
        thumbnail:"https://i.ytimg.com/vi/dVxd0tsJbVo/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB21NVn-fsnshoN-r9wfH41IVPqpg",
        time:"11 months ago",
        duration: "13:34",
        allNotes: [],
    },

]